apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-main 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mustafadincerr/a-o-apps.git
    targetRevision: HEAD
    path: app-of-apps-main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
