apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mustafadincerr/a-o-apps.git
    targetRevision: HEAD
    path: back
  destination:
    server: https://kubernetes.default.svc
    namespace: back
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
