apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-back
  labels:
    app: back
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          command: ["python"]
          args: ["-m", "http.server", "{{ .Values.containerPort }}"]

