apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:developer, applications, sync, */*, allow
    g, {{ .Values.rbac.adminUser }}, role:admin
    g, {{ .Values.rbac.developerUser }}, role:developer
