apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mustafadincerr/a-o-apps.git
    targetRevision: HEAD
    chart: front/
  destination:
    server: https://kubernetes.default.svc
    namespace: front
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
