apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-test1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: redis
    targetRevision: 20.0.03
    helm:
      values: |
        redis:
          password: asdqwe123
  destination:
    server: https://kubernetes.default.svc
    namespace: front
  syncPolicy:
    automated:
      prune: true
      selfHeal: true